package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
)

func main() {
	//get the book 'Huck Finn'
	res, err := http.Get("https://www.gutenberg.org/files/76/76-0.txt")

	if err != nil {
		log.Fatalln(err)
	}

	//Scan the page
	scanner := bufio.NewScanner(res.Body)
	defer res.Body.Close()

	// Set the split function for the canning operation
	// ScanWords is a split function for a Scanner that returns each
	// space-separated word of text, with surrounding spaces deleted.
	scanner.Split(bufio.ScanWords)

	// Create a slice to hold counts
	buckets := make([]int, 2000)

	// Loop over the words
	for scanner.Scan() {

		// Text returns the most recent token generated by a call to Scan
		// as a newly allocated string holding its bytes.
		n := HashBucket(scanner.Text())

		buckets[n]++

		fmt.Println(scanner.Text())
	}

	fmt.Println(buckets[65:123])
}

func HashBucket(word string) int {
	return int(word[0])
}
